@echo off
REM setup_pdm_dirs.bat -- creates the recommended PdM project layout.
REM
REM Run this once from the parent folder where you want "PdM" to live
REM (e.g. from "C:\work folder\"). It only creates empty folders -- you
REM still move your existing files into them afterward:
REM   - app.py, run_pipeline.bat, pipeline\ (whole folder) -> PdM\app
REM   - your existing bearing-data subfolders                -> PdM\data
REM     (rename set1_data/set2_data/set3_data below if yours differ)
REM
REM Everything under PdM\outputs is generated by the pipeline itself, one
REM subfolder per dataset (e.g. outputs\set2_data\) -- both run_pipeline.bat
REM and the dashboard's "Save outputs to disk" option write to the same
REM place, so you never have to hunt for results in two spots.

set ROOT=PdM

if exist "%ROOT%" (
    echo %ROOT% already exists -- adding any missing subfolders only.
)

mkdir "%ROOT%\app" 2>nul
mkdir "%ROOT%\app\pipeline" 2>nul
mkdir "%ROOT%\data" 2>nul
mkdir "%ROOT%\data\set1_data" 2>nul
mkdir "%ROOT%\data\set2_data" 2>nul
mkdir "%ROOT%\data\set3_data" 2>nul
mkdir "%ROOT%\outputs" 2>nul

echo.
echo Created:
echo   %ROOT%\app                                    - app.py (dashboard) + ims_pipeline.py (thin CLI wrapper)
echo   %ROOT%\app\pipeline                            - the engine itself: one file per stage
echo                                                     (ingest, features, health, classify, report, plotting, cli)
echo   %ROOT%\data                                    - point IMS_DATA_ROOT / the
echo                                                     dashboard's "Data Root" here
echo   %ROOT%\data\set1_data, set2_data, set3_data    - move your bearing data in
echo   %ROOT%\outputs                                 - CSV + plots + Markdown reports land here,
echo                                                     one subfolder per dataset (e.g. outputs\set2_data\)
echo.
echo Next steps:
echo   1. Move app.py, ims_pipeline.py, run_pipeline.bat, and the pipeline\
echo      folder (all its .py files) into %ROOT%\app
echo   2. Move your existing dataset folders into %ROOT%\data
echo   3. Set IMS_DATA_ROOT and IMS_OUTPUT_ROOT once so you never retype paths:
echo        setx IMS_DATA_ROOT "%%cd%%\%ROOT%\data"
echo        setx IMS_OUTPUT_ROOT "%%cd%%\%ROOT%\outputs"
echo      (close and reopen your terminal/dashboard after setx, it only
echo       applies to new sessions)
